global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq-exporter:9419"]

  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-exporter:9104"]
